### ISSUE TITLE
STRING

### ISSUE THREAD

**Issue by pnrobinson** [Knowledge-Graph-Hub/kg-covid-19#10]
There are many sources for PPI data, but I would suggest that we concentrate on STRING for starters.

**Comment by deepakunni3** [comment]
Download location: https://string-db.org/cgi/download.pl

**Comment by deepakunni3** [comment]
@pnrobinson Should we be mapping the proteins to their respective genes or leave it as-is?

**Comment by pnrobinson** [comment]
Depending on the use case the PPIs can be conflated with the genes or there could be links from gene to protein.
STRING uses only one protein isoform per gene.

**Comment by deepakunni3** [comment]
Thanks! I'll add the additional protein to gene edges for now 👍

**Comment by cmungall** [comment]
note there is also sars-cov-2 to human protein interactions: #31

**Comment by justaddcoffee** [comment]
closed by #34
