### ISSUE TITLE
Create a page with example queries

### ISSUE THREAD

**Issue by cmungall** [Knowledge-Graph-Hub/kg-covid-19#131]
E.g 

 - find all human gene products that interact with a sars2 gene product
 - as above, what are the functions of the viral genes
 - as above, also include drugs that target any of the gene products

Note these are just lookup/join queries, no ML inference

The queries could be cypher or sparql. I think this is better than a notebook but we could do that too. Obv this will require standing up neo4j and/or blazegraph

**Comment by justaddcoffee** [comment]
@cmungall we have example queries now (which @matentzn and I are iterating on):
https://github.com/Knowledge-Graph-Hub/kg-covid-19/tree/master/queries/sparql

It's worth considering how to display these queries before closing this ticket - what do you suggest?

**Comment by justaddcoffee** [comment]
I'm going to close via #216 - we can display example queries wherever we like via the YAML files in `queries/sparql/`
