### ISSUE TITLE
Versioning of TSV and RDF output

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#135]
Currently the TSV and RDF output goes here:
http://kg-hub.berkeleybop.io/kg-covid-19.nt.gz
http://kg-hub.berkeleybop.io/kg-covid-19.tar.gz
No versioning, just the timestamp on those files. It'd be good to add versioning in some way. 

Possible first step would be to append a timestamp to the actual file names. Eventually we probably want more formal data releases though.

**Comment by realmarcin** [comment]
would it be enough to just have a text file in repo storing the current version? then build would read and increment?

**Comment by justaddcoffee** [comment]
addressed by #332
