### ISSUE TITLE
2 of 3 test coverage badges linked on README are broken

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#138]
Need to fix the first two, or failing that could remove them

<img width="1028" alt="Screen Shot 2020-05-06 at 12 49 02 PM" src="https://user-images.githubusercontent.com/150311/81221698-05016580-8f98-11ea-83d0-0698dab66ab7.png">

**Comment by justaddcoffee** [comment]
@LucaCappelletti94 any idea what's going on here? Probably something simple

**Comment by LucaCappelletti94** [comment]
For the coveralls link we need to move the repository from your account to the new one, for the sonarcloud one instead is a bit weird, I'll try to understand what is happening.

**Comment by justaddcoffee** [comment]
Thanks @LucaCappelletti94 ! Maybe we can walk through this together when you have time.

**Comment by LucaCappelletti94** [comment]
Would it be ok for you to talk about this at 6PM tomorrow (Rome time)?

**Comment by justaddcoffee** [comment]
Sure, I just sent you an invite - talk to you then

**Comment by justaddcoffee** [comment]
Thanks @LucaCappelletti94 !!
