### ISSUE TITLE
sars-ncov-2 gene annotations

### ISSUE THREAD

**Issue by cmungall** [Knowledge-Graph-Hub/kg-covid-19#19]
ftp://ftp.uniprot.org/pub/databases/uniprot/pre_release/

The XML has GO, KW, and Rhea annotations. The GO annotations are from a mixture of Interpro2GO, UniRule and SubCell.

**Comment by cmungall** [comment]
GPAD and GPI now available:

ftp://ftp.ebi.ac.uk/pub/contrib/goa/uniprot_reviewed_sars-cov-2.gpi
ftp://ftp.ebi.ac.uk/pub/contrib/goa/uniprot_sars-cov-2.gpi
ftp://ftp.ebi.ac.uk/pub/contrib/goa/uniprot_sars-cov-2.gpa

**Comment by cmungall** [comment]
And follow this ticket for availability of go-cam: https://github.com/geneontology/go-site/issues/1431

**Comment by justaddcoffee** [comment]
I think I'll have a go at this one, if no one else has claimed it
