### ISSUE TITLE
Paragraph about COVID19 (medical aspect)

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#194]
Per Peter's suggestion, add a paragraph or a few sentences in the intro describing medical aspects of COVID19

**Comment by pnrobinson** [comment]
I took the opportunity to draft a short paragraph that seemed to work well at the very start of the introduction -- let me know if we want more detail

**Comment by justaddcoffee** [comment]
thanks @pnrobinson !
