### ISSUE TITLE
Verifying Patterns Article Type

### ISSUE THREAD

**Issue by callahantiff** [Knowledge-Graph-Hub/kg-covid-19#204]
I'm working on updating the manuscript formatting for Patterns and wanted to confirm the Article Type. The following [Article Types](https://www.cell.com/patterns/article-types) are available (descriptions copied directly from the website):  
- Research - A Research Article is a significant novel research study that often involves several techniques or approaches. This is a standard unsolicited and peer-reviewed manuscript that includes the majority of submissions. The essential findings presented in a Research Article, or significant parts, of them should not already have appeared in print or online.  

<br>

- Review - A Review Article is an authoritative, balanced, and scholarly survey of recent developments in a research field. The intent should be to tie relevant works in a complete, complementary, and cohesive manner or to provide a novel conceptual framework for seemingly disparate topics. The requirement for balance need not prevent authors from proposing a specific viewpoint; however, authors must respectfully state all perspectives. The scope of a Review Article should be broad enough that it is not dominated by the work of a single laboratory, and particularly not by the authors' own work.

<br>

- Descriptor - A Descriptor Article describes a research output as a first-class object in its own right, and the article provides the context for the production of the output—the who, what, why, when, and how of the output’s creation as well as permanently linking to the output in a way that facilitates its discoverability. Descriptor Articles can be about: Datasets, Software, Algorithms, Workflows, Infrastructures, Projects

<br>

- Previews - Previews highlight and summarize works in the current issue of Patterns or in a recent issue of another journal. Most Previews are commissioned, but timely unsolicited contributions will be considered.

<br>

- Perspectives -  Perspectives are concise opinion pieces that present a forward-thinking view of an emerging topic or provide fresh insights into published scientific works. The goal of such pieces is to both inform our readership about these emerging ideas and provide insights and ideas that will help push the field forward. The main criteria are that they should be of immediate interest to the data research community and should be written in an accessible, non-technical style. Perspectives may also be used to report the findings of key events in data science, such as symposia or focused meetings on data science topics.

<br>

- Tutorial - Tutorials are concise articles that review and give guidance on the usage of different tools, technologies, and services available to the data science community. The main criteria are that they should be of immediate interest to the data research community and should be written in an accessible, non-technical style.

<br>

- People of Data  - People of Data pieces are commissioned features dedicated to showcasing the individuals and teams (e.g., the people) behind the research. Features may include biographical information, lab or research group backstories, individual or group initiatives, achievements, outreach, etc., related to relevant published work. Whereas the achievements of PIs are often recognized through awards or invited lectures, specific recognition of the researchers doing the work behind the scenes is often neglected.

<br>

- Opinions - Opinions are purely editorial works offering a contemporary opinion from a single author (or team of authors) on a data science topic of interest to the community. Opinion articles offer a flexible format that may include anything of interest to the journal's readers, from policy debates to announcements to "matters arising" from research papers. The emphasis is on brevity, topicality, and widespread interest. 

<br>

I assume we want *Descriptor*?  @justaddcoffee @cmungall can you please confirm?

**Comment by deepakunni3** [comment]
+1 for Descriptor

**Comment by justaddcoffee** [comment]
Yeah, Descriptor I think

**Comment by cmungall** [comment]
Sounds good

**Comment by callahantiff** [comment]
Perfect, thank you for confirming! I did assume that's what you guys would say and reformatted the manuscript today to align with that submission type.
