### ISSUE TITLE
Graph should not contain BFO classes

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#210]
@realmarcin's testing revealed that our GO transform currently contains BFO classes as edge labels, like this following:

`http://purl.obolibrary.org/obo/UBERON_0009098   http://purl.obolibrary.org/obo/GO_0007565       BFO:0000067     biolink:contains_process`

Via @cmungall, we should not have BFO classes in the graph

**Comment by cmungall** [comment]
can you confirm that the column ordering here is `subj obj rel edge_label`?

if so, this is not such a serious problem, and the kg is faithfully presenting what is in uberon. This is a bug in uberon - we are using a non-existing IRI for a relationship type. I will report a bug, but we shouldn't waste time fixing ontologies when there is now major downstream consequence for us.

Here are some validation rules

 - An edge MUST NOT use a class ID as a relation ID [not violated here]
 - Database ingesters SHOULD NOT introduce BFO class IDs into the graph [not violated here]
    - rationale: a database ingester should only introduce edges between specific named entities, not abstract categories
    - here a 'database ingester' is anything that ingests from a non-ontology source, e.g chembl.
    - we expect ontologies to bring in edges (usually subClassOf) that point to abstract classes
 - All IRIs SHOULD resolve [violated here, but that is uberon's fault]
