### ISSUE TITLE
Contributing/collaborating

### ISSUE THREAD

**Issue by taylordm** [Knowledge-Graph-Hub/kg-covid-19#218]
Hi, all, Melissa H sent me over.  We're in the process of starting up our own graph database and heard about this one. Would you welcome new collaborators/help? We have a few interested people who could lend a hand in data preparation and harmonization and a wealth of expertise in covid-19 -- from biologists to virologists to informaticians. We also have collected public/individual databases and data sources that we could link in, and experts who can triage said datasets. Please contact me?

**Comment by justaddcoffee** [comment]
Hi @taylordm! 

> Would you welcome new collaborators/help? 

Yes, by all means! 

Our main needs now I think are 1) help with writing new ingests 2) testing the knowledge graph to identifying any lingering data bugs and 3) triaging data sources
