### ISSUE TITLE
biolink:provided_by edge_labels are present in the SPARQL endpoint as  <https://www.example.org/UNKNOWN/provided_by>

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#229]
### Describe the bug

Per convo with @matentzn, 
`biolink:provided_by` edge_labels are in the SPARQL endpoint
<https://www.example.org/UNKNOWN/provided_by>

### To Reproduce

Do this query:
```
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix bl: <https://w3id.org/biolink/vocab/>
prefix ex: <https://www.example.org/UNKNOWN/>
SELECT ?protein ?p ?v WHERE
  {
  ?protein bl:category bl:Protein; 
           ex:ncbi_taxid ?ncbitaxonid;
           ?p ?v .
   FILTER NOT EXISTS { 
    ?v bl:category bl:Publication . 
    ?v ex:provided_by ?scibitecord  
    . FILTER(?scibitecord="SciBite-CORD-19")}
   FILTER(?ncbitaxonid="2697049")
  }
```
on this enpoint:
http://kg-hub-rdf.berkeleybop.io/blazegraph/#query

You'll see lots of these type of triples:
`<http://identifiers.org/uniprot/A0A663DJA2> | ex:provided_by | "intact"^^<http://www.w3.org/2001/XMLSchema#string>`

(where `ex` is <https://www.example.org/UNKNOWN/>)

## Expected behavior

These triples should have this predicate: 
`https://w3id.org/biolink/vocab/provided_by`

### Version

Which version of KG-COVID-19 are you seeing the bug with? An md5 hash is most useful.

SPARQL endpoint of kg-covid-19 build from June 12, 2020

**Comment by deepakunni3** [comment]
This is fixed on `kg-covid-19` branch of KGX.

**Comment by justaddcoffee** [comment]
Thanks @deepakunni3! Fixed
