### ISSUE TITLE
Normalize STRING and IntAct protein IDs using KGX id remapping

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#235]
Basically just 

- [x] add a `bl:xrefs` from ENSPxxxxxx to UniprotKB:yyyyyyyy
using this file ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping.dat.gz

- [x] then during the merge step, we need to tell KGX to perform this ID remapping (@deepakunni3)

- [ ] confirm that IDs between STRING and IntAct are normalized

**Comment by justaddcoffee** [comment]
@deepakunni3 what's the status of this ID remapping in KGX - is the version of KGX used in requirements.txt (git+git://github.com/deepakunni3/kgx) doing this? 

I think this function could also help normalize the TTD drug IDs

**Comment by deepakunni3** [comment]
This should be working once we merged the PR.

**Comment by justaddcoffee** [comment]
Which PR? 

I think this ticket is waiting on me, IIUC, because I need to fix the Uniprot CURIE prefixes in the XREF column of STRING

**Comment by deepakunni3** [comment]
Yes, there is no PR pending. This has to do with a CURIE prefix typo that is getting in the way of doing the actual remapping.
Everything else is kosher.

**Comment by justaddcoffee** [comment]
thanks @deepakunni3 ! I'll fix this asap

**Comment by justaddcoffee** [comment]
Closing this - ID normalization between STRING and IntAct seems to work correctly 

Example of normalized ID: 
STRING nodes.tsv:
`ENSEMBL:ENSP00000215882          biolink:Protein                 UniProtKB:P53007        STRING`
IntAct nodes.tsv
`UniProtKB:P53007    txtp_human      biolink:Protein 9606    intact`

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  <http://identifiers.org/uniprot/P53007> <https://w3id.org/biolink/vocab/provided_by> ?obj .
} LIMIT 10
```
yields two `provided_by`'s
1 | "intact"^^<http://www.w3.org/2001/XMLSchema#string>
-- | --
2 | "STRING"^^<http://www.w3.org/2001/XMLSchema#string>
