### ISSUE TITLE
merge SciBite dictionary for SARS-CoV-2 proteins with curated gpi file

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/kg-covid-19#262]
**Name of the dataset**
https://github.com/SciBiteLabs/CORD19/blob/master/vocabularies-CORD-19/coronaprot.dictionary.txt

At least merge synonyms ....

**Mapping or relevant fields**
A clear and concise description of what which fields you would want to be ingested.

If possible, highlight which fields map to nodes and which fields map to edges.
Refer to [Data Preparation](https://github.com/NCATS-Tangerine/kgx/blob/master/data-preparation.md) for guidelines on how the final transformed data should be represented.

**Additional context**
Add any other context, requests, concerns.

**Comment by cmungall** [comment]
See also #261

**Comment by realmarcin** [comment]
synonyms merged
