### ISSUE TITLE
Updated information per kg-covid-19 summary document?

### ISSUE THREAD

**Issue by linikujp** [Knowledge-Graph-Hub/kg-covid-19#266]
https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/master/documentation/kg-covid-19%20data%20summary.pptx.png
The information on this slide is out-dated. There are a lot of work being done within these two months. Is there an updated slides with some statistics for current status summary for kg-covid-19? I'd like to introduce the kg to a research group as a potential data source that they can leverage.
Thanks,
Asiyah

**Comment by justaddcoffee** [comment]
Hi @linikujp - yes, that slide is getting a little outdated. 

The summary statistics [here](http://kg-hub.berkeleybop.io/merged_graph_stats.yaml) are generated automatically with each build, and as such are always up-to-date and also much more detailed.

Glad to provide more info for your into talk to the research group. Also you might find [these slides](https://docs.google.com/presentation/d/1wrRRK11x6Ds_oyBTVZ-EIzm4KqHeo0xP/edit#slide=id.g879a709c7b_0_18) useful - feel free to use them if they are helpful

**Comment by linikujp** [comment]
Thank you so much, Justin!
