### ISSUE TITLE
combined_scores from STRING ingest should be emitted as integers not strings

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#294]
### Describe the bug
Interaction scores for edges from the STRING ingest are present as integers (0-1000) in the 'combined_score' edge property:

```
subject	edge_label	object	relation	provided_by	combined_score	neighborhood	neighborhood_transferred	fusion	cooccurence	homology	coexpression	coexpression_transferred	experiments	experiments_transferred	database	database_transferred	textmining	textmining_transferred
ENSEMBL:ENSP00000000233	biolink:interacts_with	ENSEMBL:ENSP00000445175	RO:0002434	STRING	482	0	0	0	0	0	0	0	423	83	0	0	99	42
```

but these end up as strings in the RDF

### To Reproduce

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?sub <https://www.example.org/UNKNOWN/combined_score> ?obj .
} LIMIT 10
```

1 | <urn:uuid:8032326b-c348-4f38-93f4-86540b85d232> | "423"^^<http://www.w3.org/2001/XMLSchema#string>
-- | -- | --
2 | <urn:uuid:804330eb-b13d-4078-ae23-5fa3d5c6a7a5> | "423"^^<http://www.w3.org/2001/XMLSchema#string>

## Expected behavior

These combined_scores should be integers, not strings

### Version

Build queried on ~Jul 21, 2020

**Comment by deepakunni3** [comment]
This is now fixed.

**Comment by justaddcoffee** [comment]
Thanks @deepakunni3 ! +1
