### ISSUE TITLE
consider setting up a Jenkins CI

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#30]
per convo with Chris, could set up Jenkins to do CI, produce some artifacts, and detect breaking changes in upstream sources

Roughly speaking, we would:
- extract/transform/load into KGX
- output rdf
- possibly load blazegraph

**Comment by justaddcoffee** [comment]
- extract/transform/load into KGX
- output rdf

**Comment by justaddcoffee** [comment]
@wdduncan did you say you might be interested in doing this?

**Comment by wdduncan** [comment]
@justaddcoffee 
Sure. I'm interested in learning how to set up Jenkins. I've never done it though ...

**Comment by kltm** [comment]
Talking to @justaddcoffee 
- [ ] janky jenkins on a random server, at least 5G
- [ ] enough disk to deal with 1-10Gs of data per build
- [ ] ability to push to AWS
- [ ] @justaddcoffee to work on name/domain
- [ ] not a "public" server; this is understood by all interested parties
- [ ] simple commands in a simple Jenkins file
- [ ] designed to go down and be lifted elsewhere or run manually easily if there are issues

**Comment by justaddcoffee** [comment]
@wdduncan just chatted with Seth, he will have a server we can use for Jenkins ready soon, possibly by Friday (with the understanding that this server could change at any moment, so we should do things in a machine-agnostic way).

In the meantime, could you make a PR and write up a Jenkins file? It'd be something like:

```
pipeline {
    agent any 
    stages {
        stage('Build kg_covid_19') {
            steps {
                dir('./config') {
                    git(
                        url: 'https://github.com/Knowledge-Graph-Hub/kg-covid-19',
                        branch: 'master'
                    )
                    sh ''' # venv and pip stuff
                    '''
                }
            }
        }
        stage('Download') {
            steps {
                  python run.py download
            }
        }
        stage('Transform') {
            steps {
                  python run.py transform
            }
        }
        stage('Load') {
            steps {
                  python run.py load
            }
        }
        stage('Push to s3 bucket') {
            steps {
                 ???? # Need some details for this item
            }
        }
    }
}
```

**Comment by justaddcoffee** [comment]
>  @justaddcoffee to work on name/domain

I think we could just make the landing place for artifacts from this pipeline a bucket name on s3 for now, right?

**Comment by kltm** [comment]
@justaddcoffee That would be fine for now.

**Comment by justaddcoffee** [comment]
@wdduncan just fyi, @kltm and I briefly discussed this at the group hangout today, and made [this branch](https://github.com/Knowledge-Graph-Hub/kg-covid-19/tree/jenkins), which contains a Jenkinsfile we can iterate on. Jenkins UI is [here](https://build-exp.berkeleybop.io/), Seth can probably set you up with credentials.

**Comment by justaddcoffee** [comment]
@kltm quick question - what is the maximum RAM this Jenkins job should use? I did a test this weekend, and it turns out the last of the 3 steps (`python run.py load`) can use tens of Gs of RAM for say an hour or two. Just checking whether this is too much for the server running this job.

**Comment by kltm** [comment]
@justaddcoffee Use what is needed. Keep in mind that if you have multiple branches running your performance will naturally be affected. The machine is not that large: in our discussions about what was needed (https://github.com/Knowledge-Graph-Hub/kg-covid-19/issues/30#issuecomment-606908902), you indicated that not a lot of memory was needed and that you were running this on your laptop no problem--the machine was selected accordingly. That said, what is available on the machine is yours to use.

**Comment by justaddcoffee** [comment]
>  you indicated that not a lot of memory was needed and that you were running this on your laptop no problem--the machine was selected accordingly.

Yep, mea culpa. I underestimated the memory requirements a bit here

**Comment by kltm** [comment]
This is what is available on the selected machine:
```
free -h
              total        used        free      shared  buff/cache   available
Mem:            23G        2.9G         13G         11M        6.8G         20G
Swap:           46G        1.6G         44G
```
So you've like 20G to play with there...and a little fudge with the swap (although if you're using the swap you're gunna start having issues). If that is not sufficient, we'll have to do something else (and nail down the requirements).

**Comment by justaddcoffee** [comment]
Okay, I think 23G RAM, and 46G swap should work

**Comment by kltm** [comment]
If you're using more than a few GB of swap, the machine will likely stop functioning. I do not remember the rationale for the large swap in this case.

**Comment by justaddcoffee** [comment]
@wdduncan FYI I'm hacking on this now, with @deepakunni3 's  sage Jenkins advice. Hope to have this running soon to produce TSV's that we can convert to RDF and put out today, per @cmungall 's request

**Comment by wdduncan** [comment]
Great! Do you need me to join the call? I need to learn how to do this too ...

**Comment by justaddcoffee** [comment]
We can discuss at BBOP hangout I think

**Comment by justaddcoffee** [comment]
Turns out we'll need to use python3.7 b/c of bmt requirements, and python3.7 isn't available on the machine in which Jenkins is set up. So, we'll need to use a Docker image containing 3.7 - @deepakunni3 is doing this now

**Comment by justaddcoffee** [comment]
Belay that - @kltm installed python3.7, and we've got the Jenkins pipeline working now. We could (and probably should) change to use a Docker image soon-ish

**Comment by kltm** [comment]
Just noting that @kltm hackily added python3.7 and there may be necessary changes in the undefined future.
