### ISSUE TITLE
make a dashboard to display summary stats for KG-COVID-19

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#322]
Make a dashboard to display summary statistics broken down by source, similar to the Monarch qc dashboard: 
https://qc.monarchinitiative.org/

Per @cmungall , we will eventually want to see summary of QC checks (e.g violations of schema and logic in biolink-model, OWL reasoning violations) like go-rules and obo-dashboard but that can come later.

Base reference implementation:
https://github.com/cmungall/dasher

@kltm 
@kshefchek
@deepakunni3

**Comment by kltm** [comment]
I believe that the CDN should now work with CORS, but it may take a little for the caches to expire, etc.

**Comment by justaddcoffee** [comment]
Kent, @kltm said he's enabled cross-domain resource sharing for you:
https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html

Can you check?

I was planning on making a list of YAML files for you to ingest and put it on the S3 bucket, if that would simplify things

**Comment by kltm** [comment]
To clarify, while bucket access is technically possible, people should generally be using proper URLs of the form `http://kg-hub.berkeleybop.io/<SOMETHING>`

**Comment by cmungall** [comment]
This ticket is scoped quite broadly, QC can encompass quite a lot.

Plans for a general purpose semantic dashboard
https://docs.google.com/document/d/1ld73pVz_BIH22jRBZuV0RVDeSiuGyQpD1u_F9Yv9gg0/edit#

Base reference implementation:
https://github.com/cmungall/dasher

Monarch qc dashboard: https://qc.monarchinitiative.org/

I think this ticket is mostly for summary stats, which is one aspect of QC. But we will eventually want to see summary of QC checks (e.g violations of schema and logic in biolink-model, OWL reasoning violations) like go-rules and obo-dashboard but that can come later.

Implementation: sounds like we will generate YAMLs as part of release process, and use this to drive a vuepress site?

Do we want to consider a solr instance? Will make it easier to facet etc

In theory this should not be too hard. With the latest solr no schema required, can just set up a generic server and use curl to load kgx files. We may want to use something like term-expando to denormalize and make closures

**Comment by justaddcoffee** [comment]
@cmungall good point, I named this ticket too vaguely. I'm changing the name (and scope) to "make a dashboard to display summary stats", as that I think is what we have in mind in the short term. 

> Implementation: sounds like we will generate YAMLs as part of release process, and use this to drive a vuepress site?

Yes, I think that's probably the simplest solution at the moment

**Comment by justaddcoffee** [comment]
Closed thanks to @kshefchek, beautiful dashboard is [here](https://knowledge-graph-hub.github.io/kg-covid-19-dashboard/)
