### ISSUE TITLE
All but one of the SPARQL queries are broken (for MS submission)

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#342]
### Describe the bug

One of the reviewers remarked: 
`I could only get one of your example queries to return something on http://kg-hub-rdf.berkeleybop.io/blazegraph/#query I'm not sure if this is expected`

### To Reproduce

SPARQL queries are here:
https://github.com/Knowledge-Graph-Hub/kg-covid-19/tree/master/queries/sparql

Endpoint is here:
kg-hub-rdf.berkeleybop.io/blazegraph/p

## Expected behavior

All SPARQL queries should return something - the title of each describes what it should return

### Version

https://github.com/Knowledge-Graph-Hub/kg-covid-19/commit/9fd270e1b141487ee422d138cd74add87118f669

**Comment by matentzn** [comment]
All but one work:


- [query-01-cl-cat-counts](https://yasgui.triply.cc/#query=SELECT%20(COUNT(%3Fv2)%20AS%20%3Fv1)%20%3Fv0%0A%20%20WHERE%20%7B%0A%20%20%20%20%3Fv2%20%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2Fcategory%3E%20%3Fv0%0A%20%20%7D%20GROUP%20BY%20%3Fv0&endpoint=http%3A%2F%2Fkg-hub-rdf.berkeleybop.io%2Fblazegraph%2Fsparql&requestMethod=POST&tabTitle=query-01-cl-cat-counts&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)
- [query-02-sars-cov-2-prot](https://yasgui.triply.cc/#query=prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%20%20prefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%20%20prefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%20%20prefix%20bl%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0A%20%20prefix%20ex%3A%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2F%3E%0A%20%20SELECT%20%3Fprotein%20%3Fp%20%3Fv%20WHERE%0A%20%20%20%20%7B%0A%20%20%20%20%3Fprotein%20bl%3Acategory%20bl%3AProtein%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20ex%3Ancbi_taxid%20%3Fncbitaxonid%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fp%20%3Fv%20.%0A%20%20%20%20%20FILTER%20NOT%20EXISTS%20%7B%20%0A%20%20%20%20%20%20%3Fv%20bl%3Acategory%20bl%3APublication%20.%20%0A%20%20%20%20%20%20%3Fv%20ex%3Aprovided_by%20%3Fscibitecord%20%20%0A%20%20%20%20%20%20.%20FILTER(%3Fscibitecord%3D%22SciBite-CORD-19%22)%7D%0A%20%20%20%20%20FILTER(%3Fncbitaxonid%3D%222697049%22)%0A%20%20%20%20%7D&endpoint=http%3A%2F%2Fkg-hub-rdf.berkeleybop.io%2Fblazegraph%2Fsparql&requestMethod=POST&tabTitle=query-02-sars-cov-2-prot&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)
- Broken: [query-03-sars-cov-2-interactors](https://yasgui.triply.cc/#query=prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%20%20prefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%20%20prefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%20%20prefix%20bl%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0A%20%20SELECT%20%3Fcovp%20%3Fcovplab%20%3Fp%20%3Fplab%20%3Fhumanp%20%3Fhumanplab%20WHERE%0A%20%20%7B%0A%20%20%3Finteraction%20bl%3Aedge_label%20bl%3Ainteracts_with%20.%0A%20%20%3Finteraction%20bl%3Aobject%20%3Fcovp%20.%0A%20%20%3Finteraction%20bl%3Asubject%20%3Fhumanp%20.%0A%20%20%3Finteraction%20bl%3Arelation%20%3Fp%20.%0A%20%20%3Fcovp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fcovtaxon%20.%0A%20%20%3Fhumanp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fhumantaxon%20.%0A%20%20OPTIONAL%20%7B%20%3Fcovp%20rdfs%3Alabel%20%3Fcovplab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fhumanp%20rdfs%3Alabel%20%3Fhumanplab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fp%20rdfs%3Alabel%20%3Fplab%20%7D%0A%20%20%20FILTER(%3Fcovtaxon%3D%222697049%22)%0A%20%20%20FILTER(%3Fhumantaxon%3D%229606%22)%0A%20%20%7D%20LIMIT%201&endpoint=http%3A%2F%2Fkg-hub-rdf.berkeleybop.io%2Fblazegraph%2Fsparql&requestMethod=POST&tabTitle=query-03-sars-cov-2-interactors&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)
- [query-04-sars-cov-2-interactors_2nd_order](https://yasgui.triply.cc/#query=PREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0Aprefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0Aprefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0Aprefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0Aprefix%20bl%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0ASELECT%20%3Fcovp%20%3Fcovplab%20%3Fhumanp%20%3Fhumanplab%20%3Fhumanp2%20%3Fhumanp2lab%0AWHERE%20%7B%0A%20%20VALUES%20%3Fcovtaxon%20%7B%222697049%22%5E%5Exsd%3Astring%20%7D%0A%20%20VALUES%20%3Fhumantaxon%20%7B%20%229606%22%5E%5Exsd%3Astring%20%7D%0A%20%20%3Fhumanp%20bl%3Ainteracts_with%20%3Fcovp%20.%0A%20%20%3Fhumanp%20bl%3Ainteracts_with%20%3Fhumanp2%20.%0A%20%20%3Fcovp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fcovtaxon%20.%0A%20%20%3Fhumanp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fhumantaxon%20.%0A%20%20%3Fhumanp2%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fhumantaxon%20.%0A%20%20OPTIONAL%20%7B%20%3Fcovp%20rdfs%3Alabel%20%3Fcovplab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fhumanp%20rdfs%3Alabel%20%3Fhumanplab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fhumanp2%20rdfs%3Alabel%20%3Fhumanp2lab%20%7D%20.%0A%7D%0A&endpoint=http%3A%2F%2Fkg-hub-rdf.berkeleybop.io%2Fblazegraph%2Fsparql&requestMethod=POST&tabTitle=query-04-sars-cov-2-interactors_2nd_order&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)
- [query-05-sars-cov-2-interactors_druggable_2nd_order](https://yasgui.triply.cc/#query=PREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%20%20prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%20%20prefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%20%20prefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%20%20prefix%20bl%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0A%20%20SELECT%20%3Fcovp%20%3Fcovplab%20%3Fhumanp%20%3Fhumanplab%20%3Fhumanp2%20%3Fhumanp2lab%20%3Fdrug%20%3Fdruglab%0A%20%20WHERE%20%7B%0A%20%20%20%20VALUES%20%3Fcovtaxon%20%7B%222697049%22%5E%5Exsd%3Astring%20%7D%0A%20%20%20%20VALUES%20%3Fhumantaxon%20%7B%20%229606%22%5E%5Exsd%3Astring%20%7D%0A%20%20%3Fhumanp%20bl%3Ainteracts_with%20%3Fcovp%20.%0A%20%20%3Fhumanp%20bl%3Ainteracts_with%20%3Fhumanp2%20.%0A%20%20%3Fcovp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fcovtaxon%20.%0A%20%20%3Fhumanp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fhumantaxon%20.%0A%20%20%3Fhumanp2%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fhumantaxon%20.%0A%20%20%3Fhumanp2%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2FTDL%3E%20%22Tclin%22%5E%5E%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23string%3E%20.%0A%20%20%3Fdrug%20bl%3Acategory%20bl%3ADrug%3B%20bl%3Ainteracts_with%20%3Fhumanp2%20.%0A%20%20OPTIONAL%20%7B%20%3Fcovp%20rdfs%3Alabel%20%3Fcovplab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fhumanp%20rdfs%3Alabel%20%3Fhumanplab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fhumanp2%20rdfs%3Alabel%20%3Fhumanp2lab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fdrug%20rdfs%3Alabel%20%3Fdruglab%20%7D%20.%0A%20%20%7D&endpoint=http%3A%2F%2Fkg-hub-rdf.berkeleybop.io%2Fblazegraph%2Fsparql&requestMethod=POST&tabTitle=query-05-sars-cov-2-interactors_druggable_2nd_order&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)
- [query-06-provided_by_counts](https://yasgui.triply.cc/#query=prefix%20bl%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0ASELECT%20(COUNT(%3Fv2)%20AS%20%3Fv1)%20%3Fv0%0A%20%20WHERE%20%7B%0A%20%20%20%20%3Fv2%20bl%3Aprovided_by%20%3Fv0%0A%20%20%7D%20GROUP%20BY%20%3Fv0%0AORDER%20BY%20DESC(%3Fv1)%0A&endpoint=http%3A%2F%2Fkg-hub-rdf.berkeleybop.io%2Fblazegraph%2Fsparql&requestMethod=POST&tabTitle=query-06-provided_by_counts&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)

Seems like interaction links are no longer available in their reified form. I will change the query to use direct linking instead.

**Comment by matentzn** [comment]
Justin, can you review this:

- [fixed query-03-sars-cov-2-interactors](https://yasgui.triply.cc/#query=prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%20%20prefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%20%20prefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%20%20prefix%20bl%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0A%20%20SELECT%20%3Fcovp%20%3Fcovplab%20%3Fhumanp%20%3Fhumanplab%20WHERE%0A%20%20%7B%0A%20%20%3Fhumanp%20bl%3Ainteracts_with%20%3Fp%20.%0A%20%20%3Fcovp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fcovtaxon%20.%0A%20%20%3Fhumanp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fhumantaxon%20.%0A%20%20OPTIONAL%20%7B%20%3Fcovp%20rdfs%3Alabel%20%3Fcovplab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fhumanp%20rdfs%3Alabel%20%3Fhumanplab%20%7D%20.%0A%20%20OPTIONAL%20%7B%20%3Fp%20rdfs%3Alabel%20%3Fplab%20%7D%0A%20%20%20FILTER(%3Fcovtaxon%3D%222697049%22)%0A%20%20%20FILTER(%3Fhumantaxon%3D%229606%22)%0A%20%20%7D%20LIMIT%2010&endpoint=http%3A%2F%2Fkg-hub-rdf.berkeleybop.io%2Fblazegraph%2Fsparql&requestMethod=POST&tabTitle=query-03-sars-cov-2-interactors&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)

whether it is acceptable. Note: it is now missing the `p` (see old query above)! (the _way_ in which the interaction worked previously)

**Comment by matentzn** [comment]
Sorry there was a mistake now fixed.

**Comment by matentzn** [comment]
Thanks to @deepakunni3 here the correct version:

[fixed query-03-sars-cov-2-interactors](https://yasgui.triply.cc/#query=prefix%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0A%20%20prefix%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%20%20prefix%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%20%20prefix%20bl%3A%20%3Chttps%3A%2F%2Fw3id.org%2Fbiolink%2Fvocab%2F%3E%0A%20%20SELECT%20%3Fcovp%20%3Fcovplab%20%3Fp%20%3Fplab%20%3Fhumanp%20%3Fhumanplab%20WHERE%0A%20%20%7B%0A%20%20%20%20%3Finteraction%20rdf%3Apredicate%20bl%3Ainteracts_with%20.%0A%20%20%20%20%3Finteraction%20rdf%3Aobject%20%3Fcovp%20.%0A%20%20%20%20%3Finteraction%20rdf%3Asubject%20%3Fhumanp%20.%0A%20%20%20%20%3Finteraction%20bl%3Arelation%20%3Fp%20.%0A%20%20%20%20%3Fcovp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fcovtaxon%20.%0A%20%20%20%20%3Fhumanp%20bl%3Acategory%20bl%3AProtein%3B%20%3Chttps%3A%2F%2Fwww.example.org%2FUNKNOWN%2Fncbi_taxid%3E%20%3Fhumantaxon%20.%0A%20%20%20%20OPTIONAL%20%7B%20%3Fcovp%20rdfs%3Alabel%20%3Fcovplab%20%7D%20.%0A%20%20%20%20OPTIONAL%20%7B%20%3Fhumanp%20rdfs%3Alabel%20%3Fhumanplab%20%7D%20.%0A%20%20%20%20OPTIONAL%20%7B%20%3Fp%20rdfs%3Alabel%20%3Fplab%20%7D%0A%20%20%20%20%20FILTER(%3Fcovtaxon%3D%222697049%22)%0A%20%20%20%20%20FILTER(%3Fhumantaxon%3D%229606%22)%0A%20%20%7D&endpoint=http%3A%2F%2Fkg-hub-rdf.berkeleybop.io%2Fblazegraph%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table)

**Comment by deepakunni3** [comment]
To add more context to this ticket,
In earlier versions of our KG-COVID-19 N-Triples export (and the SPARQL endpoint) we used to have `biolink:subject`, `biolink:object`, `biolink:predicate` as predicates of a reified association. But this was incorrect since Biolink should not mint predicates for core RDF predicates. So subsequent versions of our export, which happened after these SPARQL Queries were written, has the following changes:
- `biolink:subject` -> `rdf:subject`
- `biolink:predicate` -> `rdf:predicate`
- `biolink:object` -> `rdf:object`
- `biolink:name` -> `rdfs:label`
