### ISSUE TITLE
Updated ensmallen_graph causes panic in some unit tests

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#349]
### Describe the bug

In `TestEdges.test_make_edges_pos_train_test_valid_edges_distinct_1_neg_train_edges_tsv`, I'm seeing a panic: 

```
        # make negative edges
        logging.info("Making negative edges")
    
        all_negative_edges = \
            pos_train_edges.sample_negatives(seed=seed,
                                             negatives_number=graph.get_edges_number(),
                                             allow_selfloops=False)
        neg_train_edges, neg_test_edges = \
>           all_negative_edges.random_holdout(seed=seed, train_percentage=train_fraction)
E       pyo3_runtime.PanicException: index out of bounds: the len is 0 but the index is 53
```

### To Reproduce

`pip install ensmallen_graph -U`
`pytest test`

see also:
https://travis-ci.org/github/Knowledge-Graph-Hub/kg-covid-19/builds/730114817

## Expected behavior

Should pass holdout unit tests

### Version

f012b45f8df0badcda4e3f40836acd082ac97076

### Additional context

Also causes problems when loading graphs because my unit tests are using deprecated args in `from_csv` (`        force_conversion_to_undirected`, possibly others)

**Comment by LucaCappelletti94** [comment]
On it!

**Comment by LucaCappelletti94** [comment]
Reproduced error, working on fixing it.

**Comment by LucaCappelletti94** [comment]
Fixed, I will close this issue when we will publish the new version. The error was caused by leaving the edge types mapping within the graph with negative edges, which cannot have edge types by definition.

**Comment by justaddcoffee** [comment]
Excellent, thanks @LucaCappelletti94 ! Ping me when the new version is published and I'll unpin this dependency

**Comment by LucaCappelletti94** [comment]
Does this pass now?

**Comment by justaddcoffee** [comment]
Yep, merged now - thanks @LucaCappelletti94
