### ISSUE TITLE
Filename error in transformed graphs

### ISSUE THREAD

**Issue by LucaCappelletti94** [Knowledge-Graph-Hub/kg-covid-19#394]
### Describe the bug
The GOCAMs node list and edge list are not named using the standard convention.

Instead of being called respectively `nodes.tsv` and  `edges.tsv` they are called `GOCAMs_nodes.tsv` and `GOCAMs_edges.tsv`.

### To Reproduce
Visit this URL: https://kg-hub.berkeleybop.io/kg-covid-19/current/transformed/GOCAMs/index.html

**Comment by justaddcoffee** [comment]
@LucaCappelletti94 - presumably we figured out a way around this? Or is this still an issue

**Comment by LucaCappelletti94** [comment]
We no longer include the transformed versions of these graphs in the current graph retrieval because of inconsistencies in the URL and file formats. We can revisit this issue in the future if it becomes necessary.
