### ISSUE TITLE
Enhance and reorganize documentation

### ISSUE THREAD

**Issue by cmungall** [Knowledge-Graph-Hub/kg-covid-19#401]
* It looks like we don't have links to the grlc queries; e.g http://grlc.io/api-git/Knowledge-Graph-Hub/kg-covid-19/subdir/queries -- we should add
 * try and consolidate CONTRIBUTING.md and https://github.com/Knowledge-Graph-Hub/kg-covid-19/wiki/How-to-help?
 * move away from gh-wiki. see what @hrshdhgd did for kgm: https://knowledge-graph-hub.github.io/kg-microbe -- I think we should align these while keeping an eye on koza plans (cc @kshefchek )

additional notes:

I personally prefer mkdocs to github wikis, or rtd for code. Most recently we have been reorganizing a lot of [linkml-based projects to use mkdocs](https://docs.google.com/document/d/1NENatAvlQ7t-KVV7H4AbqjX-K1GGARN9ebbhwEhD7DQ/edit#heading=h.p3pqhfnsb4fe), and also a lot of [ontologies to use it too](https://docs.google.com/presentation/d/1YyWYSetDML3nhNgMUmcrsw80Xx1Uf1n1dWI-A20PMa8/edit#slide=id.gb5dd3f1a69_0_769).

**Comment by justaddcoffee** [comment]
Started on a PR for this [here](https://github.com/Knowledge-Graph-Hub/kg-covid-19/pull/424). 

This PR adds sphinx documentation for all the docstring in the code -still need to add the manually created documentation.

**Comment by justaddcoffee** [comment]
Addressed by #424 and #427
