### ISSUE TITLE
unable to download kg-covid-19 data

### ISSUE THREAD

**Issue by RLWOHIO** [Knowledge-Graph-Hub/kg-covid-19#474]
Hi,
I am trying to download kg-covid-19 data, both the raw and transformed, from this link https://kg-hub.berkeleybop.io/kg-covid-19/index.html. But there is nothing there. Is there another link for downloading? I have also sent a request to the email listed on the KG-hub contact page and am waiting for a response.  Thanks.

**Comment by justaddcoffee** [comment]
@RLWOHIO very sorry for the inconvenience

Here is a Zendodo link with the 2023-01-03 build of KG-COVID-19 in KGX tsv and Ntriples format
https://zenodo.org/records/12701879

Let me know if this is what you need

**Comment by RLWOHIO** [comment]
They are very informative. I am particularly interested in the SciBite Cord-19 subset and how they are transformed from the raw data of TERMite annotated entities/co-occurrences to the final Biolink nodes/edges. If there are any additional files generated in between and available to help me better understand this process, I would love to have them as well. Thanks so much!

**Comment by justaddcoffee** [comment]
> They are very informative. I am particularly interested in the SciBite Cord-19 subset and how they are transformed from the raw data of TERMite annotated entities/co-occurrences to the final Biolink nodes/edges

you can find the code that defines how the SciBite Cord-19 data is transformed [here](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/master/kg_covid_19/transform_utils/scibite_cord/scibite_cord.py)

If you want just the subgraph for ScitBite, you could probably just do this:

`awk -F'\t' '($2 ~ /CORD:/ || $4 ~ /CORD:/)' merged-kg_edges.tsv > scibite_edges.tsv`

**Comment by RLWOHIO** [comment]
The python script transforming CORD-19 data will be very helpful. Thanks again!
