### ISSUE TITLE
Transform classes aren't passing input_dir and output_dir

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#59]
Calls to these transforms [here](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/0ff582b363671c401812a07d026b2a05df002834/kg_covid_19/transform.py#L13) aren't passing input_dir and output_dir (my fault):
```
    hpo = HpoTransform()
    hpo.run()

    zt = ZhouTransform()
    zt.run()

    dct = DrugCentralTransform()
    dct.run()

    ttd = TTDTransform()
    ttd.run()
```

Also, in `StringTransform` [here](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/0ff582b363671c401812a07d026b2a05df002834/kg_covid_19/transform_utils/string_ppi/string_ppi.py#L39), `self.output_dir` should be appending the name of the source (`/string/` or some such) to the directory.

Probably should handle all of this in `Transform.py` parent class

**Comment by deepakunni3** [comment]
Working on this now
