### ISSUE TITLE
Speed up STRING ingest

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#63]
Luca said he might want to try speeding up STRING ingest, possibly by parallelization.

[Here](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/master/kg_covid_19/transform_utils/string_ppi/string_ppi.py) is the ingest in question.

Possibly could parallelize [here](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/6ef6c06c9eb90f365e0c58822350c76d6faa92bf/kg_covid_19/transform_utils/string_ppi/string_ppi.py#L145) while reading lines, or maybe as @deepakunni3 said, [this](https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/6ef6c06c9eb90f365e0c58822350c76d6faa92bf/kg_covid_19/transform_utils/string_ppi/string_ppi.py#L172) utility fxn could be sped up

**Comment by LucaCappelletti94** [comment]
Some questions on the utility: is there any reason why it returns None?

**Comment by justaddcoffee** [comment]
> Some questions on the utility: is there any reason why it returns None?

No reason, other than to return a `type` of some kind for type-checking. Could refactor to return a boolean I guess?

**Comment by LucaCappelletti94** [comment]
Though it is possible to parse the lines using multiprocessing it is not possible to write the lines in the same way, how much memory do you think would it take to keep them in memory and write them all after the first read has finished?

**Comment by justaddcoffee** [comment]
> Though it is possible to parse the lines using multiprocessing it is not possible to write the lines in the same way, how much memory do you think would it take to keep them in memory and write them all after the first read has finished?

Not sure, but you could get some idea by running:
`python run.py transform -s StringTransform`
then looking at the size of the files generated:
`ls  -lh data/transformed/STRING/`

At least a few gigs I bet

**Comment by deepakunni3** [comment]
The file size is at 122M. So ingesting that into an in-memory data structure shouldn't be a problem at the moment. But note that we are dealing with just a subset of the original data by restricting to human PPIs. 
The actual master file is 68GB (compressed). I doubt we will ever need to parse all of the file. Just highlighting the upper bounds of memory requirements.

**Comment by justaddcoffee** [comment]
Hi @LucaCappelletti94 - for clarity, can you confirm you are working on this? @deepakunni3 said he could handle this if you are not. Just trying to avoid duplicating effort

**Comment by LucaCappelletti94** [comment]
Yes, it should be done by the end of the morning.

**Comment by LucaCappelletti94** [comment]
I see that the same "seen" list is used for check for both the already seen proteins and genes: could this cause a name clash?

**Comment by LucaCappelletti94** [comment]
I'm working on this issue [here](https://github.com/Knowledge-Graph-Hub/kg-covid-19/tree/speed_up_string).

**Comment by LucaCappelletti94** [comment]
I have refactored the code and replaced the lists with sets, so now that aspect should run a bit faster. I am not sure if parallelizing the I/O can add a significant speedup as the remaining data elaboration is minimal. What do you think?

**Comment by deepakunni3** [comment]
@LucaCappelletti94 There shouldn't be a name clash for `seen`. The identifiers are mutually exclusive for gene and protein

**Comment by justaddcoffee** [comment]
> I have refactored the code and replaced the lists with sets, so now that aspect should run a bit faster. I am not sure if parallelizing the I/O can add a significant speedup as the remaining data elaboration is minimal. What do you think?

Thanks Luca! A very dramatic speed-up, STRING ingest is now down to 2m!

```
(venv) ~/PycharmProjects/kg-emerging-viruses *speed_up_string $ time python run.py transform -s StringTransform
WARNING:ToolkitGenerator:class "pairwise interaction association" slot "interacting molecules category" does not reference an existing slot.  New slot was created.
WARNING:ToolkitGenerator:Unrecognized prefix: SEMMEDDB
[snip]
INFO:root:Parsing StringTransform
[transform.py][           transform] INFO: Parsing StringTransform

real    2m19.998s
user    2m14.680s
sys     0m2.388s
```

**Comment by LucaCappelletti94** [comment]
It almost leaves me with the doubt that I haven't done something wrong with the code: the output file looks okay? I think that other than the pythonification of the code the only real source of speed up was replacing the list with a set.

**Comment by justaddcoffee** [comment]
If this helps: 

`edges.tsv` produced from your branch and from `master` is exactly the same (see m5 hash below, `bak/` dir is produced from `master`). 

Your `nodes.tsv` has fewer entries than `master`, but the few I checked out are just extra ENSEMBL ids not mentioned in `edges.tsv`

```
(venv) ~/PycharmProjects/kg-emerging-viruses $ ls -l  data/transformed/STRING/*.tsv data/transformed/STRING/bak/*tsv
-rw-r--r--  1 jtr4v  staff  1255956605 Apr  3 11:57 data/transformed/STRING/bak/edges.tsv
-rw-r--r--  1 jtr4v  staff     2456430 Apr  3 11:57 data/transformed/STRING/bak/nodes.tsv
-rw-r--r--  1 jtr4v  staff  1255956605 Apr  5 09:12 data/transformed/STRING/edges.tsv
-rw-r--r--  1 jtr4v  staff     2391930 Apr  5 09:12 data/transformed/STRING/nodes.tsv
(venv) ~/PycharmProjects/kg-emerging-viruses $ md5 data/transformed/STRING/*.tsv data/transformed/STRING/bak/*tsv
MD5 (data/transformed/STRING/edges.tsv) = c960835ae79f6235d8b4a7be6ce4372f
MD5 (data/transformed/STRING/nodes.tsv) = 21ea74367b01086301f4a9dfba6e1bb9
MD5 (data/transformed/STRING/bak/edges.tsv) = c960835ae79f6235d8b4a7be6ce4372f
MD5 (data/transformed/STRING/bak/nodes.tsv) = 408ed8393fbce7abcf20864cee5bbd77
```

**Comment by LucaCappelletti94** [comment]
Ok! That seems promising, I was worried that the speedup was caused by some coding mistake such as an if-condition that was never met. Out of curiosity, how much time was it required on the same machine before?

**Comment by justaddcoffee** [comment]
> Out of curiosity, how much time was it required on the same machine before?

14 hours on my laptop - a very dramatic speed-up

**Comment by deepakunni3** [comment]
Wow, @LucaCappelletti94 This is amazing! A simple change made all the difference!

For posterity: In Python, `lists` are slow in lookup for membership. Whereas, `sets` are dramatically faster because of the way set stores its values: hash tables.

**Comment by justaddcoffee** [comment]
> For posterity: In Python, lists are slow in lookup for membership. Whereas, sets are dramatically faster because of the way set stores its values: hash tables.

Good to know - I didn't realize either how much quicker `sets` are

**Comment by LucaCappelletti94** [comment]
Should I proceed with the pull request?

**Comment by deepakunni3** [comment]
@LucaCappelletti94 Yes, the output looks proper. Feel free to make a PR
