### ISSUE TITLE
ingest GO

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#72]
We have GO annotations for many viral genes and drug targets - we probably need to ingest the ontology itself now. 

We'll want at least the relational graph, class labels and class categories

Per @cmungal 's notes: 

> - for ML/query purposes the most important aspect of an ontology is its relational graph. We also want at least class label and class category (for human readability and biolink compliance)
note the relational graph is simply edges such as is-a, part-of, has-input, etc. 

> for GO, use go-plus (owl or json). This connects to CHEBI, UBERON, CL, ...

Also we should use the official PURL from obofoundry.org as our download source:

> We should always use the official PURLs for download (see the ontology's page on http://obofoundry.org and look at the list of 'products')
there is typically an obo and owl version, there is increasingly an obojson version
for more on obojson

**Comment by justaddcoffee** [comment]
See also Chris's advice [here](https://github.com/Knowledge-Graph-Hub/kg-covid-19/issues/71)

**Comment by deepakunni3** [comment]
@justaddcoffee I can get started on this. Should be easy to ingest

**Comment by justaddcoffee** [comment]
Sure, thanks @deepakunni3 

Possibly could crib parts of the HPO ingest for this. Note that Chris advises ingesting the obojson or owl (not the obo, as I did for the HPO ingest)

**Comment by deepakunni3** [comment]
Thanks! I'll take a look.

Yes, I am fetching the following file for ingest: http://purl.obolibrary.org/obo/go.json

**Comment by justaddcoffee** [comment]
I think Chris mentioned it might be good to ingest go-plus?
http://purl.obolibrary.org/obo/go/extensions/go-plus.json
We'd get some extra goodies that way (Chembl, Uberon, etc)

**Comment by deepakunni3** [comment]
Aye!

**Comment by justaddcoffee** [comment]
closed by #100
