### ISSUE TITLE
Issue in ScibiteCordTransform unzipping zip file

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#79]
Seeing this on Jenkins, and I think Marcin's colleagues saw it too: 

```
14:48:38  [transform.py][           transform] INFO: Parsing StringTransform
14:54:29  INFO:root:Parsing ScibiteCordTransform
14:54:29  [transform.py][           transform] INFO: Parsing ScibiteCordTransform
14:54:29  Traceback (most recent call last):
14:54:29    File "run.py", line 81, in <module>
14:54:29      cli()
14:54:29    File "/var/lib/jenkins/workspace/ge_Graph_Hub_kg-covid-19_jenkins/config/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
14:54:29      return self.main(*args, **kwargs)
14:54:29    File "/var/lib/jenkins/workspace/ge_Graph_Hub_kg-covid-19_jenkins/config/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
14:54:29      rv = self.invoke(ctx)
14:54:29    File "/var/lib/jenkins/workspace/ge_Graph_Hub_kg-covid-19_jenkins/config/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
14:54:29      return _process_result(sub_ctx.command.invoke(sub_ctx))
14:54:29    File "/var/lib/jenkins/workspace/ge_Graph_Hub_kg-covid-19_jenkins/config/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
14:54:29      return ctx.invoke(self.callback, **ctx.params)
14:54:29    File "/var/lib/jenkins/workspace/ge_Graph_Hub_kg-covid-19_jenkins/config/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
14:54:29      return callback(*args, **kwargs)
14:54:29    File "run.py", line 59, in transform
14:54:29      kg_transform(*args, **kwargs)
14:54:29    File "/var/lib/jenkins/workspace/ge_Graph_Hub_kg-covid-19_jenkins/config/kg_covid_19/transform.py", line 48, in transform
14:54:29      t.run()
14:54:29    File "/var/lib/jenkins/workspace/ge_Graph_Hub_kg-covid-19_jenkins/config/kg_covid_19/transform_utils/scibite_cord/scibite_cord.py", line 46, in run
14:54:29      self.parse_annotations(node_handle, edge_handle, data_files[0])
14:54:29    File "/var/lib/jenkins/workspace/ge_Graph_Hub_kg-covid-19_jenkins/config/kg_covid_19/transform_utils/scibite_cord/scibite_cord.py", line 61, in parse_annotations
14:54:29      with ZipFile(data_file, 'r') as ZF:
14:54:29    File "/usr/lib/python3.7/zipfile.py", line 1258, in __init__
14:54:29      self._RealGetContents()
14:54:29    File "/usr/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
14:54:29      raise BadZipFile("File is not a zip file")
14:54:29  zipfile.BadZipFile: File is not a zip file
```

@deepakunni3 any ideas?

**Comment by deepakunni3** [comment]
@justaddcoffee Looking into it

**Comment by justaddcoffee** [comment]
See [this Jenkins run](https://build-exp.berkeleybop.io/job/Knowledge%20Graph%20Hub/job/kg-covid-19/job/jenkins/44/) for how things were set up before the stack trace above happened

**Comment by deepakunni3** [comment]
This has to do with the upstream SciBite data source. They use Git LFS to store large files. Until yesterday a wget would download LFS files. Now it doesn't do that. Unsure why.
Trying to decode the Git LFS API to find a way to download just the exact file that we need.

**Comment by deepakunni3** [comment]
Please feel free to comment out SciBite data source from our ingest. This is not going to be an easy fix

**Comment by justaddcoffee** [comment]
@deepakunni3 Okay, thanks for the update. 

I actually have a cached copy of the "good" SciBite data file. I think for now to address #80 and and also to keep things working temporarily I am going push this file to a public URL with @kltm 's help, then make a PR to ingest this file from that URL instead

**Comment by cmungall** [comment]
@jamesmalone maybe there is another way to release the files

**Comment by justaddcoffee** [comment]
> @jamesmalone maybe there is another way to release the files

That would really helpful

**Comment by jamesmalone** [comment]
Not sure why your previous strategy no longer works!
Sure, try this S3 location:
https://s3.eu-west-2.amazonaws.com/scibite.covid19data/CORD19/annotated-cord19/CORD-19_1_3.zip

**Comment by jamesmalone** [comment]
Oh I see the issue, we're over our bandwidth subscription for LSF. Wish github would email me when this happens! I've increased this so you should be able to keep pilling from git if you need, but otherwise the S3 is there.

**Comment by deepakunni3** [comment]
@jamesmalone Thank you for the S3 bucket location.

Much appreciated!

**Comment by justaddcoffee** [comment]
thanks @jamesmalone !
