### ISSUE TITLE
ChEMBL

### ISSUE THREAD

**Issue by pnrobinson** [Knowledge-Graph-Hub/kg-covid-19#8]
https://www.ebi.ac.uk/chembl/

especially antivirals and targets

**Comment by sundaram-covid19-biohack** [comment]
Hi @justaddcoffee , 

Just to confirm:

For the **targets**:
I filtered the targets at ChEMBL by selecting organism == 'Homo sapiens' and downloaded a tab-delimited file containing 5,626 records.

For the **antivirals**:
I filtered the drugs by selecting the 'ANTIVIRALS FOR SYSTEMIC USE' under the ATC Class. Level 2 section and downloaded a tab-delimited file containing 67 records.

Please advise if my filter criteria are correct.

Thank you,
Jay

**Comment by justaddcoffee** [comment]
> Please advise if my filter criteria are correct.

Yes, I think this filtering is reasonable. 

If it's easy enough, you could create variables for these two filtering criteria (organism and ATC class) at the top of your class and set them to 'Homo sapiens' and  'ANTIVIRALS FOR SYSTEMIC USE', respectively? It's possible we'll want to tweak these

**Comment by sundaram-covid19-biohack** [comment]
Thank you for confirming.

Sounds good- I will add the filtering criteria to the new classes (ChEMBLTargetTransform  and the ChEMBLDrugTransform) as you've suggested.

**Comment by sundaram-covid19-biohack** [comment]
Per the [instructions](https://github.com/Knowledge-Graph-Hub/kg-covid-19/wiki/How-to-help#write-code-to-ingest-data), I will define 3 columns/fields in the node records as:

1. id
2. name
3. category

Here are the available fields in the ChEMBL targets dataset:
ChEMBL ID
Name
UniProt Accessions
Type 
Organism
Compounds
Activities
Tax ID
Species Group Flag

Will ignore the following fields:
Tax ID
Species Group Flag

First node type will comprise: ['ChEMBL ID', 'Name', 'Type']

My impression is that each of the following should have their own nodes:
UniProt Accessions (where each value in the pipe-separated list should have its own node)
Organism
Compounds (some ChEMBL numeric i.e.: unsigned integer value)
Activities (some ChEMBL numeric i.e.: unsigned integer value)

Please advise:

1. What should be the id, name, category for each of those nodes?
For UniProt Accession node:
id => the actual value e.g.: Q13547
name => does transform software need to retrieve and parse data from the UniProt webservice?
category => does transform software need to retrieve and parse data from the UniProt webservice?

For Organism node:
id => ?
name => the actual value e.g.: "Homo sapiens"
category => ? 

For Compounds node:
id => the actual value e.g.: 995
name => does the transform software need to retrieve and parse additional data from the ChEMBL webservice?
category => does the transform software need to retrieve and parse additional data from the ChEMBL webservice?

For Activities node:
id => the actual value e.g.: 998
name => does the transform software need to retrieve and parse additional data from the ChEMBL webservice?
category => does the transform software need to retrieve and parse additional data from the ChEMBL webservice?

2. For the edge records, what should be the 'edge_label' and 'relation' values in each case?

**Comment by justaddcoffee** [comment]
> My impression is that each of the following should have their own nodes:
> UniProt Accessions (where each value in the pipe-separated list should have its own node)
> Organism
> Compounds (some ChEMBL numeric i.e.: unsigned integer value)
> Activities (some ChEMBL numeric i.e.: unsigned integer value)

I would say for now, let's keep it simple. Just make two types of nodes: targets and compounds. 

For each target, you can add organism as an extra column. (NCBITaxon:9606 for all these I think.)

You can add activities as an extra field on the edge connecting target and compound. 

For target nodes:
id: a CURIE with Uniprot ID, e.g. `UniProtKB:Q13547`
name: whatever name chembl uses for the entry, or else just use the ID above
category: `biolink:Protein`
organism: NCBITaxon:XXXX (XXXX = 9606 if these are all human)

For compound (drug) nodes:
id: a CURIE for the drug using CHEMBL ID, e.g. `CHEMBL:12345`
name: whatever name chembl uses for the entry, or else just use the ID above
category: `biolink:Drug`
organism: NCBITaxon:XXXX (XXXX = 9606 if these are all human)

For edges: 
subject: drug id above, in CURIE form
edge_label: `biolink:interacts_with`
object: target id above, in CURIE form
relation: `RO:0002436`
activity: whatever activity CHEMBL notes
[more columns if you want, whatever is available for this target -> drug combination]

Make sense?

**Comment by justaddcoffee** [comment]
@deepakunni3 feel free to correct me in any of the above is off base (Deepak is the biolink expert)

**Comment by sundaram-covid19-biohack** [comment]
@justaddcoffee , 
Thanks for the guidance.  
I have modified the software accordingly.
Will wait to see if Deepak has additional instructions.

**Comment by sundaram-covid19-biohack** [comment]
@justaddcoffee ,

Do you have specifications for how the ChEMBL drug (antiviral) dataset should be converted into nodes and edge nodes?

FYI - Here is the first record (header: value):

Parent Molecule: CHEMBL3989506
Synonyms: TROMANTADINE
Research Codes: 
Phase: 0
Applicants: 
USAN Stem: '-mantadine'
USAN Year: 
USAN Stem Definition: antivirals/antiparkinsonians (adamantane derivatives)
USAN Stem Substem: '-mantadine(-mantadine)'
First Approval: 
ATC Codes: J05AC03 | D06BB02
Level 4 ATC Codes: J05AC - Cyclic amines | D06BB - Antivirals
Level 3 ATC Codes: J05A - DIRECT ACTING ANTIVIRALS | D06B - CHEMOTHERAPEUTICS FOR TOPICAL USE
Level 2 ATC Codes: J05 - ANTIVIRALS FOR SYSTEMIC USE | D06 - ANTIBIOTICS AND CHEMOTHERAPEUTICS FOR DERMATOLOGICAL USE
Level 1 ATC Codes: J - ANTIINFECTIVES FOR SYSTEMIC USE | D - DERMATOLOGICALS
Indication Class: 
Patent: 
Drug Type: 1:Synthetic Small Molecule
Passes Rule of Five: True
First In Class: False
Chirality: Single Stereoisomer
Prodrug: False
Oral: False
Parenteral: False
Topical: False
Black Box: False
Availability Type: Unknown
Withdrawn Year: 
Withdrawn Reason: 
Withdrawn Country: 
Withdrawn Class: 
Smiles: CN(C)CCOCC(=O)NC12CC3CC(CC(C3)C1)C2

**Comment by deepakunni3** [comment]
@sundaram-covid19-biohack Thank you for making a start on this! 👍 
@justaddcoffee Yes, you summarized it well. 

We can refine it further in subsequent iterations, if need be.

**Comment by justaddcoffee** [comment]
> @justaddcoffee ,
> 
> Do you have specifications for how the ChEMBL drug (antiviral) dataset should be converted into nodes and edge nodes?
> 
> FYI - Here is the first record (header: value):

I'd say make a node for each antiviral that looks like:

id: a CURIE , like CHEMBL:CHEMBL3989506
name: first synonym, or the id above
category: biolink:Drug
[add a column for each item you enumerated above, from synonyms to smiles.

If I understand correctly, none of the data in this file imply any drug -> drug target links. So, I'm not sure we need any edges for this file.

Did you find any data files for drug -> viral protein drug target in Chembl?

**Comment by sundaram-covid19-biohack** [comment]
@justaddcoffee ,

What I understand from your previous post is that the columns in the nodes should be:
id
name
category

and then all of the following:

1. Parent Molecule
2. Synonyms
3. Research Codes
4. Phase
5. Applicants
6. USAN Stem
7. USAN Year
8. USAN Stem Definition
9. USAN Stem Substem
10. First Approval
11. ATC Codes
12. Level 4 ATC Codes
13. Level 3 ATC Codes
14. Level 2 ATC Codes
15. Level 1 ATC Codes
16. Indication Class
17. Patent
18. Drug Type
19. Passes Rule of Five
20. First In Class
21. Chirality
22. Prodrug
23. Oral
24. Parenteral
25. Topical
26. Black Box
27. Availability Type
28. Withdrawn Year
29. Withdrawn Reason
30. Withdrawn Country
31. Withdrawn Class
32. Smiles

Questions:

1. How do we handle columns that do not have a value reported in the ChEMBL dataset?  'N/A'? 'NA', empty string?

2. Should we insert the values in the Synonym column into the node.name column and also into a node.synonyms column since "synonym" may convey (valuable) info itself?*

3. How should boolean values be inserted into the KG?  True or true?  False or false?  Something else?

Thank you.


*  As an aside, I seem to recall from back in the days when I wrote software for loading GO and SO into GMOD's chado CV module, some ontologists used terms like "broad"-, "narrow"- and "exact" to further describe the synonyms.

**Comment by justaddcoffee** [comment]
closed by #139
