### ISSUE TITLE
Produce and publish RDF

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#80]
Produce some RDF from all current sources, especially CORD19: 

- download, transform, load -> nodes.tsv + edges.tsv
- transform to TTL using KGX

~~blocked by #79~~

**Comment by justaddcoffee** [comment]
Waiting to confirm that [this](https://build-exp.berkeleybop.io/job/Knowledge%20Graph%20Hub/job/kg-covid-19/job/jenkins/) Jenkins job runs to completion. Then:

- [ ] add a Jenkins stage to transform to TTL using KGX
- [ ] update Publish stage to push merged nodes and edges and TTL to https://idg.berkeleybop.io/

**Comment by justaddcoffee** [comment]
>  get current Jenkins pipeline running green to completion

Still waiting on `run.py load` to finish - 3 days and counting. I think STRING is slowing things down quite a bit.

**Comment by deepakunni3** [comment]
The whole run finished in 3 hours an 42 mins on a laptop (including STRING).
Something else is happening on the Jenkins instance. What is the specification of the Jenkins instance?

**Comment by justaddcoffee** [comment]
From #30, @kltm says that these are the mem specs on the Jenkins machine:

```
free -h
              total        used        free      shared  buff/cache   available
Mem:            23G        2.9G         13G         11M        6.8G         20G
Swap:           46G        1.6G         44G
```

Not sure of the other specs (CPU, disk space, etc)

**Comment by kltm** [comment]
Try:
```
di -h
cat /proc/cpuinfo
```

**Comment by justaddcoffee** [comment]
It's likely that what's going on here is that we're dipping into swap, and that's an order of magnitude slower on this Jenkins instance compared with Deepak's laptop (which I think has an SSD drive and therefore fast swap). 

Just chatted with Deepak, and he's going to refactor KGX a bit to lower the memory footprint

**Comment by justaddcoffee** [comment]
Thanks @deepakunni3 for adding ntriples output to KGX!
Added a stage to Jenkins to convert TSV to NT, and an additional command to push ntriples to S3, [running now](https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-covid-19/job/jenkins/4/)

**Comment by justaddcoffee** [comment]
Done - the graph in RDF triples (and of course TSV) is link here in Wiki, in the download knowledge graph section:
https://github.com/Knowledge-Graph-Hub/kg-covid-19/wiki
