### ISSUE TITLE
Add S3 dropoff pipeline example for Jenkins

### ISSUE THREAD

**Issue by kltm** [Knowledge-Graph-Hub/kg-covid-19#82]
Add S3 dropoff pipeline example for Jenkins.

This ticket can be closed when a demonstrator exists for how to use S3 to push data out from the Jenkins pipeline to idg.berkeleybop.io .

**Comment by kltm** [comment]
@justaddcoffee This is functionally done on `issue-82-s3-push`. Scavange, close, etc. as needed.

**Comment by justaddcoffee** [comment]
excellent, thanks @kltm
