### ISSUE TITLE
Jenkins credentials for Deepak and Bill

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#85]
@kltm could we give @wdduncan and @deepakunni3 credentials to log in and administer Jenkins here? 
https://build-exp.berkeleybop.io/job/Knowledge%20Graph%20Hub/

(Please close if they already have cred's, or don't want them)

**Comment by kltm** [comment]
They will need to send me their preferred email address, user name, and have Signal ready to use. When done:
- [ ] @wdduncan 
- [ ] @deepakunni3
