### ISSUE TITLE
Ingest MONDO

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-covid-19#97]
**Name of the dataset**
MONDO disease ontology 

**Mapping or relevant fields**
Probably should ingest this obojson: 
http://purl.obolibrary.org/obo/mondo.json

We need disease IDs and also axioms that link to HPO phenotypes

Similar ingest to #48

**Comment by deepakunni3** [comment]
@justaddcoffee I am going to take this one since I am already in the realm of ontologies with GO.

**Comment by justaddcoffee** [comment]
I think we might need equivalence axioms to other disease ontologies, since drug indications might reference these instead of MONDO

**Comment by justaddcoffee** [comment]
> @justaddcoffee I am going to take this one since I am already in the realm of ontologies with GO.

Great, go for it @deepakunni3

**Comment by justaddcoffee** [comment]
closed by #100
